# Generated by Django 3.1 on 2020-11-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/%Y%m%d')),
                ('mel', models.ImageField(blank=True, null=True, upload_to='mel/%Y%m%d')),
                ('prediction', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('etc', '기타')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('pos', '양성'), ('neg', '음성'), ('none', '알수없음')], max_length=50)),
            ],
        ),
    ]
