# Generated by Django 3.1 on 2020-11-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cough',
            name='audio',
            field=models.FileField(upload_to='audio/%Y%m%d'),
        ),
    ]
