# Generated by Django 3.1 on 2020-11-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xray',
            name='neg_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xray',
            name='pos_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
