# Generated by Django 3.1 on 2020-11-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/%Y%m%d')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/%Y%m%d')),
                ('mel', models.ImageField(blank=True, null=True, upload_to='mel/%Y%m%d')),
                ('prediction', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi', to='inferences.patient')),
            ],
        ),
    ]
