# Generated by Django 3.1 on 2020-11-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0002_auto_20201123_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
