# Generated by Django 3.1 on 2020-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img/%Y%m%d')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/%Y%m%d')),
                ('mel', models.ImageField(blank=True, null=True, upload_to='mel/%Y%m%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
