# Generated by Django 3.1 on 2020-11-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidata',
            name='neg_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multidata',
            name='pos_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
