# Generated by Django 3.1 on 2020-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coughaudio',
            name='mel',
            field=models.ImageField(blank=True, null=True, upload_to='mel/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='coughaudio',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y%m%d'),
        ),
    ]
