# Generated by Django 3.1 on 2020-10-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xray', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chestxray',
            name='heatmap',
        ),
        migrations.RemoveField(
            model_name='chestxray',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='chestxray',
            name='user',
        ),
    ]
